// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Balance struct {
	WalletID  int64              `json:"wallet_id"`
	Currency  string             `json:"currency"`
	Amount    pgtype.Numeric     `json:"amount"`
	Available pgtype.Numeric     `json:"available"`
	Pending   pgtype.Numeric     `json:"pending"`
	UserID    int64              `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Migration struct {
	Version     int32              `json:"version"`
	AppliedAt   pgtype.Timestamptz `json:"applied_at"`
	Description pgtype.Text        `json:"description"`
}

type Minter struct {
	ID                      string             `json:"id"`
	OrganizationID          string             `json:"organization_id"`
	SupportedCurrencies     []byte             `json:"supported_currencies"`
	SupportedCountries      []byte             `json:"supported_countries"`
	Fees                    []byte             `json:"fees"`
	Limits                  []byte             `json:"limits"`
	Status                  string             `json:"status"`
	ApiType                 pgtype.Text        `json:"api_type"`
	ApiBaseUrl              pgtype.Text        `json:"api_base_url"`
	ApiVersion              pgtype.Text        `json:"api_version"`
	ApiEndpoints            []byte             `json:"api_endpoints"`
	ApiAuthentication       []byte             `json:"api_authentication"`
	ApiKeys                 pgtype.Text        `json:"api_keys"`
	ApiStatus               pgtype.Text        `json:"api_status"`
	WebhookUrl              pgtype.Text        `json:"webhook_url"`
	WebhookSecret           pgtype.Text        `json:"webhook_secret"`
	CreatedAt               time.Time          `json:"created_at"`
	UpdatedAt               time.Time          `json:"updated_at"`
	LastHealthCheck         pgtype.Timestamptz `json:"last_health_check"`
	HealthStatus            pgtype.Text        `json:"health_status"`
	MinterName              pgtype.Text        `json:"minter_name"`
	SettlementBankName      pgtype.Text        `json:"settlement_bank_name"`
	SettlementAccountNumber pgtype.Text        `json:"settlement_account_number"`
	SettlementRoutingNumber pgtype.Text        `json:"settlement_routing_number"`
	SettlementCurrency      pgtype.Text        `json:"settlement_currency"`
	SettlementMethod        pgtype.Text        `json:"settlement_method"`
	ContactName             pgtype.Text        `json:"contact_name"`
	ContactEmail            pgtype.Text        `json:"contact_email"`
	ContactPhone            pgtype.Text        `json:"contact_phone"`
}

type MinterToken struct {
	ID           string             `json:"id"`
	MinterID     pgtype.Text        `json:"minter_id"`
	TokenAddress pgtype.Text        `json:"token_address"`
	ChainName    pgtype.Text        `json:"chain_name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	WalletID     pgtype.Int8        `json:"wallet_id"`
	TokenName    pgtype.Text        `json:"token_name"`
}

type MintingBankDeposit struct {
	ID            string             `json:"id"`
	MinterID      pgtype.Text        `json:"minter_id"`
	MintHistoryID pgtype.Text        `json:"mint_history_id"`
	BankTxNumber  pgtype.Text        `json:"bank_tx_number"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type MintingHistory struct {
	ID                      string             `json:"id"`
	Type                    string             `json:"type"`
	UserID                  int64              `json:"user_id"`
	Status                  string             `json:"status"`
	MinterID                string             `json:"minter_id"`
	MinterName              string             `json:"minter_name"`
	Amount                  string             `json:"amount"`
	Currency                string             `json:"currency"`
	TransactionHash         pgtype.Text        `json:"transaction_hash"`
	Fees                    string             `json:"fees"`
	CreatedAt               time.Time          `json:"created_at"`
	CompletedAt             pgtype.Timestamptz `json:"completed_at"`
	DestinationWalletID     pgtype.Int8        `json:"destination_wallet_id"`
	DestinationNetwork      pgtype.Text        `json:"destination_network"`
	DestinationAddress      pgtype.Text        `json:"destination_address"`
	SourceWalletID          pgtype.Int8        `json:"source_wallet_id"`
	SourceNetwork           pgtype.Text        `json:"source_network"`
	SourceAddress           pgtype.Text        `json:"source_address"`
	TokenAddress            string             `json:"token_address"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	CreatorOrganizationID   string             `json:"creator_organization_id"`
	CreatorOrganizationName string             `json:"creator_organization_name"`
}

type Organization struct {
	ID                 string             `json:"id"`
	Name               string             `json:"name"`
	Description        pgtype.Text        `json:"description"`
	LogoUrl            pgtype.Text        `json:"logo_url"`
	Website            pgtype.Text        `json:"website"`
	RegistrationNumber pgtype.Text        `json:"registration_number"`
	TaxID              pgtype.Text        `json:"tax_id"`
	Industry           pgtype.Text        `json:"industry"`
	Country            pgtype.Text        `json:"country"`
	Address            pgtype.Text        `json:"address"`
	IsVerified         pgtype.Bool        `json:"is_verified"`
	VerificationDate   pgtype.Timestamptz `json:"verification_date"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
}

type OrganizationBank struct {
	ID                      string             `json:"id"`
	OrganizationID          pgtype.Text        `json:"organization_id"`
	SettlementBankName      pgtype.Text        `json:"settlement_bank_name"`
	SettlementAccountNumber pgtype.Text        `json:"settlement_account_number"`
	SettlementRoutingNumber pgtype.Text        `json:"settlement_routing_number"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type OtcQuote struct {
	ID                  string      `json:"id"`
	UserID              int64       `json:"user_id"`
	SourceCurrency      string      `json:"source_currency"`
	DestinationCurrency string      `json:"destination_currency"`
	Amount              string      `json:"amount"`
	Side                string      `json:"side"`
	Rate                string      `json:"rate"`
	CounterAmount       string      `json:"counter_amount"`
	Fee                 string      `json:"fee"`
	ExpiresAt           time.Time   `json:"expires_at"`
	ClientReferenceID   pgtype.Text `json:"client_reference_id"`
	Status              pgtype.Text `json:"status"`
	CreatedAt           time.Time   `json:"created_at"`
	SourceNetwork       pgtype.Text `json:"source_network"`
	TargetNetwork       pgtype.Text `json:"target_network"`
	PriceType           pgtype.Text `json:"price_type"`
	ProviderID          pgtype.Text `json:"provider_id"`
}

type Recipient struct {
	ID            string             `json:"id"`
	UserID        int64              `json:"user_id"`
	Name          string             `json:"name"`
	Blockchain    string             `json:"blockchain"`
	Network       string             `json:"network"`
	Address       string             `json:"address"`
	Status        string             `json:"status"`
	Reference     pgtype.Text        `json:"reference"`
	RiskScore     pgtype.Text        `json:"risk_score"`
	LastTransfer  pgtype.Text        `json:"last_transfer"`
	TransferCount pgtype.Int4        `json:"transfer_count"`
	IsContract    pgtype.Bool        `json:"is_contract"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type TransactionSignature struct {
	ID         string             `json:"id"`
	WalletID   int64              `json:"wallet_id"`
	UnsignedTx []byte             `json:"unsigned_tx"`
	SignedTx   []byte             `json:"signed_tx"`
	Status     string             `json:"status"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Transfer struct {
	ID                  string      `json:"id"`
	UserID              int64       `json:"user_id"`
	RecipientID         string      `json:"recipient_id"`
	Amount              string      `json:"amount"`
	SourceCurrency      string      `json:"source_currency"`
	DestinationCurrency string      `json:"destination_currency"`
	Status              string      `json:"status"`
	CreatedAt           time.Time   `json:"created_at"`
	SourceWalletID      int64       `json:"source_wallet_id"`
	Reference           pgtype.Text `json:"reference"`
	SourceNetwork       pgtype.Text `json:"source_network"`
	DestinationNetwork  pgtype.Text `json:"destination_network"`
}

type User struct {
	ID                int64              `json:"id"`
	Email             string             `json:"email"`
	Password          string             `json:"password"`
	KycStatus         pgtype.Text        `json:"kyc_status"`
	Role              string             `json:"role"`
	OrganizationID    pgtype.Text        `json:"organization_id"`
	ExternalReference pgtype.Text        `json:"external_reference"`
	Status            pgtype.Text        `json:"status"`
	KycVerifiedAt     pgtype.Timestamptz `json:"kyc_verified_at"`
	NotificationEmail pgtype.Bool        `json:"notification_email"`
	NotificationSms   pgtype.Bool        `json:"notification_sms"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type UserProfile struct {
	UserID      int64              `json:"user_id"`
	FirstName   pgtype.Text        `json:"first_name"`
	LastName    pgtype.Text        `json:"last_name"`
	Phone       pgtype.Text        `json:"phone"`
	Country     pgtype.Text        `json:"country"`
	DateOfBirth pgtype.Text        `json:"date_of_birth"`
	Address     pgtype.Text        `json:"address"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Wallet struct {
	ID             int64              `json:"id"`
	UserID         int64              `json:"user_id"`
	Blockchain     string             `json:"blockchain"`
	Address        string             `json:"address"`
	Status         pgtype.Text        `json:"status"`
	CreatedAt      time.Time          `json:"created_at"`
	Details        pgtype.Text        `json:"details"`
	OrganizationID pgtype.Text        `json:"organization_id"`
	ProviderType   string             `json:"provider_type"`
	WalletProvider pgtype.Text        `json:"wallet_provider"`
	Network        string             `json:"network"`
	DefaultWallet  bool               `json:"default_wallet"`
	Description    pgtype.Text        `json:"description"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type WalletAccessControl struct {
	WalletID         int64              `json:"wallet_id"`
	UserID           int64              `json:"user_id"`
	AccessLevel      string             `json:"access_level"`
	DailyLimit       pgtype.Numeric     `json:"daily_limit"`
	ApprovalRequired pgtype.Bool        `json:"approval_required"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type WalletProvider struct {
	ID           string             `json:"id"`
	Name         string             `json:"name"`
	ProviderType string             `json:"provider_type"`
	Credentials  []byte             `json:"credentials"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
