// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Transaction Signature Operations
	CreateTransactionSignature(ctx context.Context, arg CreateTransactionSignatureParams) (TransactionSignature, error)
	CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error)
	DeleteExpiredTransactionSignatures(ctx context.Context) error
	DeleteWallet(ctx context.Context, id int64) error
	GetTransactionSignature(ctx context.Context, id string) (TransactionSignature, error)
	GetWallet(ctx context.Context, id int64) (Wallet, error)
	GetWalletBalances(ctx context.Context, walletID int64) ([]GetWalletBalancesRow, error)
	GetWalletByAddress(ctx context.Context, arg GetWalletByAddressParams) (Wallet, error)
	GetWalletForUpdate(ctx context.Context, id int64) (Wallet, error)
	GetWalletsByOrganization(ctx context.Context, organizationID pgtype.Text) ([]Wallet, error)
	ListPendingTransactionSignatures(ctx context.Context, limit int32) ([]TransactionSignature, error)
	ListWallets(ctx context.Context, arg ListWalletsParams) ([]Wallet, error)
	UpdateTransactionSignature(ctx context.Context, arg UpdateTransactionSignatureParams) (TransactionSignature, error)
	UpdateTransactionSignatureStatus(ctx context.Context, arg UpdateTransactionSignatureStatusParams) (TransactionSignature, error)
	UpdateWallet(ctx context.Context, arg UpdateWalletParams) (Wallet, error)
	UpdateWalletBalance(ctx context.Context, arg UpdateWalletBalanceParams) (Balance, error)
	UpdateWalletStatus(ctx context.Context, arg UpdateWalletStatusParams) (Wallet, error)
	UpsertWalletBalance(ctx context.Context, arg UpsertWalletBalanceParams) (Balance, error)
}

var _ Querier = (*Queries)(nil)
