// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: wallet.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransactionSignature = `-- name: CreateTransactionSignature :one

INSERT INTO transaction_signatures (
  id,
  wallet_id,
  unsigned_tx,
  status,
  expires_at
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING id, wallet_id, unsigned_tx, signed_tx, status, expires_at, created_at, updated_at
`

type CreateTransactionSignatureParams struct {
	ID         string             `json:"id"`
	WalletID   int64              `json:"wallet_id"`
	UnsignedTx []byte             `json:"unsigned_tx"`
	Status     string             `json:"status"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

// Transaction Signature Operations
func (q *Queries) CreateTransactionSignature(ctx context.Context, arg CreateTransactionSignatureParams) (TransactionSignature, error) {
	row := q.db.QueryRow(ctx, createTransactionSignature,
		arg.ID,
		arg.WalletID,
		arg.UnsignedTx,
		arg.Status,
		arg.ExpiresAt,
	)
	var i TransactionSignature
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.UnsignedTx,
		&i.SignedTx,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWallet = `-- name: CreateWallet :one
INSERT INTO wallets (
  organization_id,
  provider_type,
  wallet_provider,
  blockchain,
  network,
  address,
  status,
  default_wallet,
  description
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, user_id, blockchain, address, status, created_at, details, organization_id, provider_type, wallet_provider, network, default_wallet, description, updated_at
`

type CreateWalletParams struct {
	OrganizationID pgtype.Text `json:"organization_id"`
	ProviderType   string      `json:"provider_type"`
	WalletProvider pgtype.Text `json:"wallet_provider"`
	Blockchain     string      `json:"blockchain"`
	Network        string      `json:"network"`
	Address        string      `json:"address"`
	Status         pgtype.Text `json:"status"`
	DefaultWallet  bool        `json:"default_wallet"`
	Description    pgtype.Text `json:"description"`
}

func (q *Queries) CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, createWallet,
		arg.OrganizationID,
		arg.ProviderType,
		arg.WalletProvider,
		arg.Blockchain,
		arg.Network,
		arg.Address,
		arg.Status,
		arg.DefaultWallet,
		arg.Description,
	)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Blockchain,
		&i.Address,
		&i.Status,
		&i.CreatedAt,
		&i.Details,
		&i.OrganizationID,
		&i.ProviderType,
		&i.WalletProvider,
		&i.Network,
		&i.DefaultWallet,
		&i.Description,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredTransactionSignatures = `-- name: DeleteExpiredTransactionSignatures :exec
DELETE FROM transaction_signatures
WHERE expires_at < now() AND status = 'pending_signature'
`

func (q *Queries) DeleteExpiredTransactionSignatures(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredTransactionSignatures)
	return err
}

const deleteWallet = `-- name: DeleteWallet :exec
DELETE FROM wallets
WHERE id = $1
`

func (q *Queries) DeleteWallet(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteWallet, id)
	return err
}

const getTransactionSignature = `-- name: GetTransactionSignature :one
SELECT id, wallet_id, unsigned_tx, signed_tx, status, expires_at, created_at, updated_at FROM transaction_signatures
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTransactionSignature(ctx context.Context, id string) (TransactionSignature, error) {
	row := q.db.QueryRow(ctx, getTransactionSignature, id)
	var i TransactionSignature
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.UnsignedTx,
		&i.SignedTx,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWallet = `-- name: GetWallet :one
SELECT id, user_id, blockchain, address, status, created_at, details, organization_id, provider_type, wallet_provider, network, default_wallet, description, updated_at FROM wallets
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetWallet(ctx context.Context, id int64) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWallet, id)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Blockchain,
		&i.Address,
		&i.Status,
		&i.CreatedAt,
		&i.Details,
		&i.OrganizationID,
		&i.ProviderType,
		&i.WalletProvider,
		&i.Network,
		&i.DefaultWallet,
		&i.Description,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalletBalances = `-- name: GetWalletBalances :many
SELECT currency, amount, available, pending
FROM balances
WHERE wallet_id = $1
`

type GetWalletBalancesRow struct {
	Currency  string         `json:"currency"`
	Amount    pgtype.Numeric `json:"amount"`
	Available pgtype.Numeric `json:"available"`
	Pending   pgtype.Numeric `json:"pending"`
}

func (q *Queries) GetWalletBalances(ctx context.Context, walletID int64) ([]GetWalletBalancesRow, error) {
	rows, err := q.db.Query(ctx, getWalletBalances, walletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWalletBalancesRow{}
	for rows.Next() {
		var i GetWalletBalancesRow
		if err := rows.Scan(
			&i.Currency,
			&i.Amount,
			&i.Available,
			&i.Pending,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWalletByAddress = `-- name: GetWalletByAddress :one
SELECT id, user_id, blockchain, address, status, created_at, details, organization_id, provider_type, wallet_provider, network, default_wallet, description, updated_at FROM wallets
WHERE blockchain = $1 AND network = $2 AND address = $3
LIMIT 1
`

type GetWalletByAddressParams struct {
	Blockchain string `json:"blockchain"`
	Network    string `json:"network"`
	Address    string `json:"address"`
}

func (q *Queries) GetWalletByAddress(ctx context.Context, arg GetWalletByAddressParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWalletByAddress, arg.Blockchain, arg.Network, arg.Address)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Blockchain,
		&i.Address,
		&i.Status,
		&i.CreatedAt,
		&i.Details,
		&i.OrganizationID,
		&i.ProviderType,
		&i.WalletProvider,
		&i.Network,
		&i.DefaultWallet,
		&i.Description,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalletForUpdate = `-- name: GetWalletForUpdate :one
SELECT id, user_id, blockchain, address, status, created_at, details, organization_id, provider_type, wallet_provider, network, default_wallet, description, updated_at FROM wallets
WHERE id = $1 LIMIT 1
FOR NO KEY UPDATE
`

func (q *Queries) GetWalletForUpdate(ctx context.Context, id int64) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWalletForUpdate, id)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Blockchain,
		&i.Address,
		&i.Status,
		&i.CreatedAt,
		&i.Details,
		&i.OrganizationID,
		&i.ProviderType,
		&i.WalletProvider,
		&i.Network,
		&i.DefaultWallet,
		&i.Description,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalletsByOrganization = `-- name: GetWalletsByOrganization :many
SELECT id, user_id, blockchain, address, status, created_at, details, organization_id, provider_type, wallet_provider, network, default_wallet, description, updated_at FROM wallets
WHERE organization_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetWalletsByOrganization(ctx context.Context, organizationID pgtype.Text) ([]Wallet, error) {
	rows, err := q.db.Query(ctx, getWalletsByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Wallet{}
	for rows.Next() {
		var i Wallet
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Blockchain,
			&i.Address,
			&i.Status,
			&i.CreatedAt,
			&i.Details,
			&i.OrganizationID,
			&i.ProviderType,
			&i.WalletProvider,
			&i.Network,
			&i.DefaultWallet,
			&i.Description,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingTransactionSignatures = `-- name: ListPendingTransactionSignatures :many
SELECT id, wallet_id, unsigned_tx, signed_tx, status, expires_at, created_at, updated_at FROM transaction_signatures
WHERE status = 'pending_signature' AND (expires_at IS NULL OR expires_at > now())
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) ListPendingTransactionSignatures(ctx context.Context, limit int32) ([]TransactionSignature, error) {
	rows, err := q.db.Query(ctx, listPendingTransactionSignatures, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TransactionSignature{}
	for rows.Next() {
		var i TransactionSignature
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.UnsignedTx,
			&i.SignedTx,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWallets = `-- name: ListWallets :many
SELECT id, user_id, blockchain, address, status, created_at, details, organization_id, provider_type, wallet_provider, network, default_wallet, description, updated_at FROM wallets
WHERE 
  ($1::text IS NULL OR status = $1) AND
  ($2::text IS NULL OR blockchain = $2) AND
  ($3::text IS NULL OR organization_id = $3)
ORDER BY created_at DESC
LIMIT $4
OFFSET $5
`

type ListWalletsParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Column3 string `json:"column_3"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListWallets(ctx context.Context, arg ListWalletsParams) ([]Wallet, error) {
	rows, err := q.db.Query(ctx, listWallets,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Wallet{}
	for rows.Next() {
		var i Wallet
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Blockchain,
			&i.Address,
			&i.Status,
			&i.CreatedAt,
			&i.Details,
			&i.OrganizationID,
			&i.ProviderType,
			&i.WalletProvider,
			&i.Network,
			&i.DefaultWallet,
			&i.Description,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransactionSignature = `-- name: UpdateTransactionSignature :one
UPDATE transaction_signatures
SET 
  signed_tx = $2,
  status = $3,
  updated_at = now()
WHERE id = $1
RETURNING id, wallet_id, unsigned_tx, signed_tx, status, expires_at, created_at, updated_at
`

type UpdateTransactionSignatureParams struct {
	ID       string `json:"id"`
	SignedTx []byte `json:"signed_tx"`
	Status   string `json:"status"`
}

func (q *Queries) UpdateTransactionSignature(ctx context.Context, arg UpdateTransactionSignatureParams) (TransactionSignature, error) {
	row := q.db.QueryRow(ctx, updateTransactionSignature, arg.ID, arg.SignedTx, arg.Status)
	var i TransactionSignature
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.UnsignedTx,
		&i.SignedTx,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTransactionSignatureStatus = `-- name: UpdateTransactionSignatureStatus :one
UPDATE transaction_signatures
SET 
  status = $2,
  updated_at = now()
WHERE id = $1
RETURNING id, wallet_id, unsigned_tx, signed_tx, status, expires_at, created_at, updated_at
`

type UpdateTransactionSignatureStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateTransactionSignatureStatus(ctx context.Context, arg UpdateTransactionSignatureStatusParams) (TransactionSignature, error) {
	row := q.db.QueryRow(ctx, updateTransactionSignatureStatus, arg.ID, arg.Status)
	var i TransactionSignature
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.UnsignedTx,
		&i.SignedTx,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWallet = `-- name: UpdateWallet :one
UPDATE wallets
SET
  description = COALESCE($1, description),
  default_wallet = COALESCE($2, default_wallet),
  updated_at = now()
WHERE id = $3
RETURNING id, user_id, blockchain, address, status, created_at, details, organization_id, provider_type, wallet_provider, network, default_wallet, description, updated_at
`

type UpdateWalletParams struct {
	Description   pgtype.Text `json:"description"`
	DefaultWallet pgtype.Bool `json:"default_wallet"`
	ID            int64       `json:"id"`
}

func (q *Queries) UpdateWallet(ctx context.Context, arg UpdateWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, updateWallet, arg.Description, arg.DefaultWallet, arg.ID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Blockchain,
		&i.Address,
		&i.Status,
		&i.CreatedAt,
		&i.Details,
		&i.OrganizationID,
		&i.ProviderType,
		&i.WalletProvider,
		&i.Network,
		&i.DefaultWallet,
		&i.Description,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWalletBalance = `-- name: UpdateWalletBalance :one
UPDATE balances
SET 
  amount = amount + $1,
  updated_at = now()
WHERE wallet_id = $2 AND currency = $3
RETURNING wallet_id, currency, amount, available, pending, user_id, created_at, updated_at
`

type UpdateWalletBalanceParams struct {
	Delta    pgtype.Numeric `json:"delta"`
	WalletID int64          `json:"wallet_id"`
	Currency string         `json:"currency"`
}

func (q *Queries) UpdateWalletBalance(ctx context.Context, arg UpdateWalletBalanceParams) (Balance, error) {
	row := q.db.QueryRow(ctx, updateWalletBalance, arg.Delta, arg.WalletID, arg.Currency)
	var i Balance
	err := row.Scan(
		&i.WalletID,
		&i.Currency,
		&i.Amount,
		&i.Available,
		&i.Pending,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWalletStatus = `-- name: UpdateWalletStatus :one
UPDATE wallets
SET 
  status = $2,
  updated_at = now()
WHERE id = $1
RETURNING id, user_id, blockchain, address, status, created_at, details, organization_id, provider_type, wallet_provider, network, default_wallet, description, updated_at
`

type UpdateWalletStatusParams struct {
	ID     int64       `json:"id"`
	Status pgtype.Text `json:"status"`
}

func (q *Queries) UpdateWalletStatus(ctx context.Context, arg UpdateWalletStatusParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, updateWalletStatus, arg.ID, arg.Status)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Blockchain,
		&i.Address,
		&i.Status,
		&i.CreatedAt,
		&i.Details,
		&i.OrganizationID,
		&i.ProviderType,
		&i.WalletProvider,
		&i.Network,
		&i.DefaultWallet,
		&i.Description,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertWalletBalance = `-- name: UpsertWalletBalance :one
INSERT INTO balances (
  wallet_id,
  currency,
  amount,
  available,
  pending,
  user_id
) VALUES (
  $1, $2, $3, $4, $5, $6
)
ON CONFLICT (wallet_id, currency) 
DO UPDATE SET
  amount = EXCLUDED.amount,
  available = EXCLUDED.available,
  pending = EXCLUDED.pending,
  updated_at = now()
RETURNING wallet_id, currency, amount, available, pending, user_id, created_at, updated_at
`

type UpsertWalletBalanceParams struct {
	WalletID  int64          `json:"wallet_id"`
	Currency  string         `json:"currency"`
	Amount    pgtype.Numeric `json:"amount"`
	Available pgtype.Numeric `json:"available"`
	Pending   pgtype.Numeric `json:"pending"`
	UserID    int64          `json:"user_id"`
}

func (q *Queries) UpsertWalletBalance(ctx context.Context, arg UpsertWalletBalanceParams) (Balance, error) {
	row := q.db.QueryRow(ctx, upsertWalletBalance,
		arg.WalletID,
		arg.Currency,
		arg.Amount,
		arg.Available,
		arg.Pending,
		arg.UserID,
	)
	var i Balance
	err := row.Scan(
		&i.WalletID,
		&i.Currency,
		&i.Amount,
		&i.Available,
		&i.Pending,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
